### ISSUE TITLE
ERROR message format from pino.child({worker: 'worker_id'}) is different from INFO

### ISSUE THREAD

**Issue by d52b8** [pinojs/pino-pretty#113]
``` shell
[2020-07-02 16:26:54.307 +0000] INFO  (17236 on xxx): Info
    worker: "worker_id"
[2020-07-02 16:26:54.308 +0000] ERROR (17236 on xxx): Error
    Error: Error
        at Object.fn (/xxxxx/App.js:60:19)
        at async /xxxxx/node_modules/agenda/lib/job/run.js:78:9
worker: worker_id
```

**Comment by jsumners** [comment]
Would you like to submit a PR?
