### ISSUE TITLE
translateTime option causes TypeError: Invalid date

### ISSUE THREAD

**Issue by rmuchall** [pinojs/pino-pretty#14]
When using the following options pretty-pino crashes with the error message:
```
TypeError: Invalid date
```
(I'm trying to display the logged date/time in a human readable format)
Thanks! :)
```
pino({
    level: "trace",
    prettyPrint: {
        colorize: true,
        translateTime: true
    }
});
```

```
TypeError: Invalid date
    at C:\Work\TypeScript\node_modules\dateformat\lib\dateformat.js:39:17
    at formatTime (C:\Work\TypeScript\node_modules\pino-pretty\index.js:44:10)
    at pretty (C:\Work\TypeScript\node_modules\pino-pretty\index.js:112:18)
    at Object.write (C:\Work\TypeScript\node_modules\pino\lib\tools.js:170:25)
    at Pino.write (C:\Work\TypeScript\node_modules\pino\lib\proto.js:101:15)
    at Pino.LOG [as info] (C:\Work\TypeScript\node_modules\pino\lib\tools.js:32:26)
    at Object.<anonymous> (C:\Work\TypeScript\src\main.ts:16:5)
    at Module._compile (module.js:649:14)
    at Module.m._compile (C:\Work\TypeScript\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
```

**Comment by mcollina** [comment]
what are you logging? can you provide a full example?

**Comment by mcollina** [comment]
I think the problem is due to using pino@5, that’s not production ready yet! I think this is a bug for the pino v5 branch IMHO.
@davidmarkclements can you please have a look?

**Comment by jsumners** [comment]
The mainline release of `pino-pretty` is designed to work with `pino@4`. You can try `pino-pretty@2.0.0-rc.1` if you want to use `pino@5`.

**Comment by rmuchall** [comment]
This bug also occurs if using:
`
"pino": "5.0.0-rc.5",
"pino-pretty": "2.0.0-rc.1",
`

**Comment by davidmarkclements** [comment]
Ron could you please try it next-major branch of pino-pretty directly - if
it works I'll do an rc release of pino-pretty
