### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by btmorex** [pinojs/pino-pretty#23]
I'm getting the following error regularly with the latest pino-pretty:

```
TypeError: Cannot read property 'split' of undefined
    at joinLinesWithIndentation (/home/avery/dev/20songs/node_modules/pino-pretty/index.js:199:27)
    at filterObjects (/home/avery/dev/20songs/node_modules/pino-pretty/index.js:222:13)
    at pretty (/home/avery/dev/20songs/node_modules/pino-pretty/index.js:193:15)
    at Object.write (/home/avery/dev/20songs/node_modules/pino/lib/tools.js:208:25)
    at Pino.write (/home/avery/dev/20songs/node_modules/pino/lib/proto.js:98:15)
    at Pino.LOG [as error] (/home/avery/dev/20songs/node_modules/pino/lib/tools.js:34:21)
    at CachingSoundCloudApi.request (/home/avery/dev/20songs/src/soundcloud/api.js:32:15)
    at <anonymous>
```

Nothing has changed on my side except updating dependencies.

**Comment by mcollina** [comment]
Which versions are you using? Can you add a snippet? I _thought_ I fixed this.

**Comment by btmorex** [comment]
```
$ npm ls pino pino-pretty
20songs@0.8.35 /home/avery/dev/20songs
├─┬ hapi-pino@5.0.1
│ ├── pino@5.0.1  deduped
│ └── pino-pretty@2.0.1 
└── pino@5.0.1 
```

Trying to reproduce with a simplistic test case, but no luck so far. FWIW, I'm initializing like so:

```javascript
pino({
  level: config.debug ? 'debug' : 'info',
  prettyPrint: env === 'development',
  serializers: {err: pino.stdSerializers.err},
});
```

and the actual log line is:

```javascript
log.error(err, `waiting for ${delay} seconds`);
```

**Comment by btmorex** [comment]
Turns out changing the log line to:

```javascript
log.error({err}, `waiting for ${delay} seconds`);
```

so I guess I'm not sure why it was working before.

**Comment by mcollina** [comment]
```js
log.error(err, `waiting for ${delay} seconds`);
```

This should be supported. But I cannot really reproduce, can you add a full snippet?

**Comment by btmorex** [comment]
```javascript
'use strict';

const pino = require('pino');
const request = require('request-promise');
const {StatusCodeError} = require('request-promise/errors');

const log = pino({
  prettyPrint: true,
});

log.error(new StatusCodeError(500, undefined, {}, {}));
```
