### ISSUE TITLE
colorette causing "Cannot read property 'env' of undefined" error

### ISSUE THREAD

**Issue by iwa** [pinojs/pino-pretty#237]
installed pino-pretty in a new project, and ran into this issue
it also happens when i'm telling pino to use pino-pretty into the code 

i'm on node 16.9.1, typescript 4.4.3

```shell
node . | yarn pino-pretty
yarn run v1.22.11
$ /Users/iwa/prod/idcbyt/node_modules/.bin/pino-pretty
/Users/iwa/prod/idcbyt/node_modules/pino-pretty/node_modules/colorette/index.cjs:6
const env = process["default"].env || {};
                               ^

TypeError: Cannot read property 'env' of undefined
    at Object.<anonymous> (/Users/iwa/prod/idcbyt/node_modules/pino-pretty/node_modules/colorette/index.cjs:6:32)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/iwa/prod/idcbyt/node_modules/pino-pretty/index.js:3:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mcollina** [comment]
@kibertoad something went wrong somewhere :/

**Comment by mcollina** [comment]
thx

**Comment by iwa** [comment]
thanks for fixing the issue so quickly <3
