### ISSUE TITLE
customPrettifiers error doesn't work with ignore option

### ISSUE THREAD

**Issue by Allain55** [pinojs/pino-pretty#260]
Running this example:

```
const pino = require('pino')

const logger = pino({
	'prettyPrint': {
		'ignore': 'random',
		'customPrettifiers': {
			'error': (err) => {
				console.log('given', err); // err is {}
				
				return err.stack ?? err.message ?? err; // this will be {}
			}
		}
	},
});

logger.error({'error': new Error('message')});
```

Gives this error:
```
const lines = input.split(/\r?\n/)
                      ^

TypeError: input.split is not a function
at joinLinesWithIndentation (%PROJECT%/pino-pretty/lib/utils.js:144:23)
at prettifyError (%PROJECT%/pino-pretty/lib/utils.js:459:23)
at %PROJECT%/pino-pretty/lib/utils.js:409:15
at Array.forEach (<anonymous>)
    at prettifyObject (%PROJECT%/pino-pretty/lib/utils.js:401:26)
    at pretty (%PROJECT%/pino-pretty/index.js:152:32)
    at Object.write (%PROJECT%/pino/lib/tools.js:320:25)
    at Pino.write (%PROJECT%/pino/lib/proto.js:190:10)
    at Pino.LOG [as error] (%PROJECT%/pino/lib/tools.js:58:21)
    at Object.<anonymous> (%PROJECT%/example.js:16:8)
```

The problem is that when the filterLog method clones the given log params the value of log.error will be an empty object

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Allain55** [comment]
I'll try to create a PR. rfdc doesn't support cloning Error so it needs to be serialized first
