### ISSUE TITLE
Getting DataCloneError when using customPrettifiers.

### ISSUE THREAD

**Issue by Akash187** [pinojs/pino-pretty#289]
### My Code

```
import logger from 'pino'

const log = logger({
	transport: {
		target: 'pino-pretty',
		options: {
			ignore: 'pid,hostname',
			translateTime: 'SYS:standard',
			timestampKey: 'time',
			customPrettifiers: {
				time: (timestamp: any) => `🕰 ${timestamp}`
			}
		}
	}
})

export default log
```

### Error
```
akashkumarseth@Akashs-MacBook-Pro node-with-typescript % yarn dev
yarn run v1.22.15
$ ts-node-dev --respawn --transpile-only src/app.ts
[INFO] 01:17:27 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.4)
DataCloneError: (timestamp) => `🕰 ${timestamp}` could not be cloned.
    at new Worker (node:internal/worker:244:17)
    at createWorker (/Users/akashkumarseth/Desktop/Learn/Node/node-with-typescript/node_modules/thread-stream/index.js:50:18)
    at new ThreadStream (/Users/akashkumarseth/Desktop/Learn/Node/node-with-typescript/node_modules/thread-stream/index.js:204:19)
    at buildStream (/Users/akashkumarseth/Desktop/Learn/Node/node-with-typescript/node_modules/pino/lib/transport.js:39:18)
    at transport (/Users/akashkumarseth/Desktop/Learn/Node/node-with-typescript/node_modules/pino/lib/transport.js:111:10)
    at normalizeArgs (/Users/akashkumarseth/Desktop/Learn/Node/node-with-typescript/node_modules/pino/lib/tools.js:409:16)
    at pino (/Users/akashkumarseth/Desktop/Learn/Node/node-with-typescript/node_modules/pino/pino.js:84:28)
    at Object.<anonymous> (/Users/akashkumarseth/Desktop/Learn/Node/node-with-typescript/src/utils/logger.ts:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/akashkumarseth/Desktop/Learn/Node/node-with-typescript/node_modules/source-map-support/source-map-support.js:568:25)
[ERROR] 01:17:28 DataCloneError: (timestamp) => `🕰 ${timestamp}` could not be cloned.
```

Any help is much appreciated.

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/20afab9a9fbe211e5c43260b84f77ef39fff4e7c/docs/transports.md?plain=1#L80-L97

**Comment by Akash187** [comment]
Thanks, @jsumners for the quick response. Finally, I read the README carefully and fixed it.
