### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ronag** [pinojs/pino-pretty#40]
```
3|deepstream  | [1540590387184] FATAL (deepstream/51447 on Roberts-MacBook-Pro.local): error caused exit
3|deepstream  |     err: {
3|deepstream  |       "type": "TypeError",
3|deepstream  |       "message": "Cannot read property 'split' of undefined",
3|deepstream  |       "stack":
3|deepstream  |           TypeError: Cannot read property 'split' of undefined
3|deepstream  |               at joinLinesWithIndentation (/Users/ronagy/GitHub/nxtedition/nxt/deepstream/node_modules/pino-pretty/index.js:199:27)
3|deepstream  |               at filterObjects (/Users/ronagy/GitHub/nxtedition/nxt/deepstream/node_modules/pino-pretty/index.js:226:13)
3|deepstream  |               at pretty (/Users/ronagy/GitHub/nxtedition/nxt/deepstream/node_modules/pino-pretty/index.js:193:15)
3|deepstream  |               at Object.write (/Users/ronagy/GitHub/nxtedition/nxt/deepstream/node_modules/pino/lib/tools.js:261:25)
3|deepstream  |               at Pino.write (/Users/ronagy/GitHub/nxtedition/nxt/deepstream/node_modules/pino/lib/proto.js:99:15)
3|deepstream  |               at Pino.LOG [as error] (/Users/ronagy/GitHub/nxtedition/nxt/deepstream/node_modules/pino/lib/tools.js:39:21)
3|deepstream  |               at _db.put.err (/Users/ronagy/GitHub/nxtedition/nxt/deepstream/src/record/record-handler.js:215:22)
3|deepstream  |               at /Users/ronagy/GitHub/nxtedition/nxt/deepstream/node_modules/levelup/lib/levelup.js:196:5
```

**Comment by ronag** [comment]
```js
   const leveldown = require('leveldown')
    this._db = leveldown('./nxt-key')
    this._db.open(err => {
      this._logger.error({ err })
    })
```

**Comment by mcollina** [comment]
Can you post a full snippet?

Il giorno sab 27 ott 2018 alle 00:57 Robert Nagy <notifications@github.com>
ha scritto:

**Comment by ronag** [comment]
> Can you post a full snippet?

Sorry I've dropped this project. Just looking through old logs. Feel free to close...

**Comment by ronag** [comment]
yarn.lock
```yml
pino-pretty@^2.2.2:
  version "2.2.2"
  resolved "https://registry.yarnpkg.com/pino-pretty/-/pino-pretty-2.2.2.tgz#4bba2d1a89458bdc3be6e4f15bcf12c126ddfd82"
  integrity sha512-SYOquIE2vNBwIGpnTxg5v6fYYeweWZJm0+ezz0FFqX8kdxlxy0boucbF6rKqZ30htB4natzWZ4K835gxsqn/9g==
  dependencies:
    args "^5.0.0"
    chalk "^2.3.2"
    dateformat "^3.0.3"
    fast-json-parse "^1.0.3"
    jmespath "^0.15.0"
    pump "^3.0.0"
    readable-stream "^3.0.2"
    split2 "^3.0.0"
```

**Comment by jsumners** [comment]
I’m sorry, I do not follow any of this.

**Comment by ronag** [comment]
Look at https://github.com/pinojs/pino-pretty/blob/master/index.js#L226

if `value[keys[i]]` is `undefined` then `undefined` will be passed to `joinLinesWithIndentation` which will case a null ref.

**Comment by ronag** [comment]
https://github.com/pinojs/pino-pretty/blob/master/index.js#L223 should probable also check that `value[keys[i]] !== undefined`

Remember

```js
typeof JSON.stringify(undefined) === 'undefined'
```

**Comment by ronag** [comment]
I think just doing `logger.error({ err: undefined })` should reproduce the problem...

**Comment by mcollina** [comment]
Would you like to send a PR?
