### ISSUE TITLE
Crash when logging integer

### ISSUE THREAD

**Issue by Tiim** [pinojs/pino-pretty#69]
When i directly log a number with console.log without using pino then peno-pretty crashes with the following error message:

```js
/code/node_modules/pino-pretty/lib/utils.js:178
   if ('level' in log === false) return undefined
               ^

 TypeError: Cannot use 'in' operator to search for 'level' in 2
     at prettifyLevel (/code/node_modules/pino-pretty/lib/utils.js:178:15)
     at pretty (/code/node_modules/pino-pretty/index.js:85:29)
     at Transform.transform [as _transform] (/code/node_modules/pino-pretty/bin.js:38:18)
     at Transform._read (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_transform.js:177:10)
     at Transform._write (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_transform.js:164:83)
     at doWrite (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_writable.js:405:139)
     at writeOrBuffer (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_writable.js:394:5)
     at Transform.Writable.write (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_writable.js:303:11)
     at Transform.ondata (/code/node_modules/split2/node_modules/readable-stream/lib/_stream_readable.js:662:20)
     at Transform.emit (events.js:196:13)
```

The following snipped in my code (fastify server) will produde this crash:
```js
console.log(index); // index = 2
```

**Comment by jsumners** [comment]
Looks like a `Number.isFinite(log)` check should be added at https://github.com/pinojs/pino-pretty/blob/a0631872bd65a01faf14c850348fb3b575ffff2e/index.js#L68

Care to submit a PR?

**Comment by Tiim** [comment]
I would love to, but I don't have time at the moment.

**Comment by Tiim** [comment]
Thanks #70 seems to fixed it 👍
