### ISSUE TITLE
Crash when logging date

### ISSUE THREAD

**Issue by Tiim** [pinojs/pino-pretty#72]
When i directly log JSON.stringified date with console.log without using pino then peno-pretty crashes with the following error message:

```js
/code/node_modules/pino-pretty/lib/utils.js:178
   if ('level' in log === false) return undefined
               ^

 TypeError: Cannot use 'in' operator to search for 'level' in 2019-05-31T00:00:00.000Z
     at prettifyLevel (/code/node_modules/pino-pretty/lib/utils.js:178:15)
     at pretty (/code/node_modules/pino-pretty/index.js:85:29)
     at Transform.transform [as _transform] (/code/node_modules/pino-pretty/bin.js:38:18)
     at Transform._read (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_transform.js:177:10)
     at Transform._write (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_transform.js:164:83)
     at doWrite (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_writable.js:405:139)
     at writeOrBuffer (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_writable.js:394:5)
     at Transform.Writable.write (/code/node_modules/pino-pretty/node_modules/readable-stream/lib/_stream_writable.js:303:11)
     at Transform.ondata (/code/node_modules/split2/node_modules/readable-stream/lib/_stream_readable.js:662:20)
     at Transform.emit (events.js:196:13)
```

The following snipped in my code (fastify server) will produde this crash:
```js
const value = JSON.stringify(new Date());
console.log(value);
```
I have not tested if this only works with stringified dates or if this is a bug when a string with start and end "quotes" gets logged.

I know this is already my second crash report, but apparently I'm a talent for finding crash bugs in pino-pretty 😅

**Comment by mcollina** [comment]
Would you mind sending a PR?

Il giorno gio 27 giu 2019 alle 15:02 Tiim <notifications@github.com> ha
scritto:

**Comment by jsumners** [comment]
A plain string is valid JSON, thus it gets past the check:

https://github.com/pinojs/pino-pretty/blob/a6b20327581ade620a7533be0d0f4b7ee2123660/index.js#L56-L65

Probably need another `isObject` check _after_ JSON parsing to determine if we can go forward at:

https://github.com/pinojs/pino-pretty/blob/a6b20327581ade620a7533be0d0f4b7ee2123660/index.js#L68-L70
